spring:
  datasource:
    url: jdbc:mysql://localhost:3306/finance
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    path: /api-docs