POST http://localhost:8080/users/register 
Content-Type: application/json

{ "name":"asd", "email": "fdd@gmail.com", "password": "Asv@123" }

### 
POST http://localhost:8080/users/login
Content-Type: application/json

{ "email": "abc@gmail.com", "password": "Abc@123" } 
